//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.22 at 03:43:17 PM EEST 
//


package coffeeMachine;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the coffeeMachine package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: coffeeMachine
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CoffeeMachineDTO }
     * 
     */
    public CoffeeMachineDTO createCoffeeMachine() {
        return new CoffeeMachineDTO();
    }

    /**
     * Create an instance of {@link CoffeeMachineDTO.Money }
     * 
     */
    public CoffeeMachineDTO.Money createCoffeeMachineMoney() {
        return new CoffeeMachineDTO.Money();
    }

    /**
     * Create an instance of {@link CoffeeMachineDTO.Drinks }
     * 
     */
    public CoffeeMachineDTO.Drinks createCoffeeMachineDrinks() {
        return new CoffeeMachineDTO.Drinks();
    }

    /**
     * Create an instance of {@link CoffeeMachineDTO.Money.Coin }
     * 
     */
    public CoffeeMachineDTO.Money.Coin createCoffeeMachineMoneyCoin() {
        return new CoffeeMachineDTO.Money.Coin();
    }

    /**
     * Create an instance of {@link CoffeeMachineDTO.Drinks.Drink }
     * 
     */
    public CoffeeMachineDTO.Drinks.Drink createCoffeeMachineDrinksDrink() {
        return new CoffeeMachineDTO.Drinks.Drink();
    }

}
