//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.23 at 11:51:09 AM EEST 
//


package coffee_machine.storages.transformers.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drinks" type="{}drinks"/>
 *         &lt;element name="money" type="{}money"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drinks",
    "money"
})
@XmlRootElement(name = "coffeeMachine")
public class CoffeeMachineDTO {

    @XmlElement(required = true)
    protected DrinksDTO drinks;
    @XmlElement(required = true)
    protected MoneyDTO money;

    /**
     * Gets the value of the drinks property.
     * 
     * @return
     *     possible object is
     *     {@link DrinksDTO }
     *     
     */
    public DrinksDTO getDrinks() {
        return drinks;
    }

    /**
     * Sets the value of the drinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrinksDTO }
     *     
     */
    public void setDrinks(DrinksDTO value) {
        this.drinks = value;
    }

    /**
     * Gets the value of the money property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyDTO }
     *     
     */
    public MoneyDTO getMoney() {
        return money;
    }

    /**
     * Sets the value of the money property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyDTO }
     *     
     */
    public void setMoney(MoneyDTO value) {
        this.money = value;
    }

}
