//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.23 at 11:51:09 AM EEST 
//


package coffeeMachine.dto.coffeeMachine;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the coffeeMachine.DTO.coffeeMachineDTO package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class CoffeeMachineTDOFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: coffeeMachine.DTO.coffeeMachineDTO
     * 
     */
    public CoffeeMachineTDOFactory() {
    }

    /**
     * Create an instance of {@link CoffeeMachineDTO }
     * 
     */
    public CoffeeMachineDTO createCoffeeMachine() {
        return new CoffeeMachineDTO();
    }

    /**
     * Create an instance of {@link DrinksDTO }
     * 
     */
    public DrinksDTO createDrinks() {
        return new DrinksDTO();
    }

    /**
     * Create an instance of {@link MoneyDTO }
     * 
     */
    public MoneyDTO createMoney() {
        return new MoneyDTO();
    }

    /**
     * Create an instance of {@link CoinDTO }
     * 
     */
    public CoinDTO createCoin() {
        return new CoinDTO();
    }

    /**
     * Create an instance of {@link DrinkDTO }
     * 
     */
    public DrinkDTO createDrink() {
        return new DrinkDTO();
    }

}
